apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    directory:
      include:
        - https://github.com/knative/operator/releases/download/knative-v1.8.0/operator.yaml
  destination:
    namespace: knative-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
